language: java

jdk:
- oraclejdk8

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

cache:
  directories:
  - $HOME/.m2/repository

# skip the default install step
install: true

script:
- cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy